trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Test
  displayName: 'Test Job'
  steps:
  - checkout: self
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Build the application'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/dist'
      artifactName: 'drop'
      publishLocation: 'Container'

# Limit concurrency to 1 for this pipeline
pr:
  branches:
    include:
    - '*'
  maxConcurrent: 1
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'